# Generated by Django 3.2.6 on 2021-10-24 21:38

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='36.9847, 86.4560', max_length=63),
            preserve_default=False,
        ),
    ]
