# Generated by Django 3.2.6 on 2021-10-31 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='location',
            field=models.CharField(max_length=50),
        ),
    ]
