# Generated by Django 3.2.6 on 2021-11-27 19:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0003_alter_activity_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
