# Generated by Django 3.2.6 on 2021-09-26 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion_Forum', '0003_forum_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forum',
            old_name='files',
            new_name='file_field',
        ),
    ]
