# Generated by Django 3.2.6 on 2021-09-26 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion_Forum', '0004_rename_files_forum_file_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='file_field',
        ),
    ]
