# Generated by Django 3.2.6 on 2021-09-26 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion_Forum', '0005_remove_forum_file_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
