# Generated by Django 3.2.6 on 2021-09-27 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion_Forum', '0006_forum_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='link',
        ),
    ]
