# Generated by Django 3.2.6 on 2021-11-29 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('F', 'Food'), ('E', 'Entertainment'), ('T', 'Travel'), ('S', 'Sport'), ('Ed', 'Education')], max_length=2)),
            ],
        ),
    ]
