# Generated by Django 3.2.6 on 2021-11-29 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0002_auto_20211128_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='totalCost',
            field=models.DecimalField(decimal_places=2, max_digits=40),
        ),
    ]
