# Generated by Django 3.2.6 on 2021-11-01 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_name', models.CharField(max_length=50)),
                ('meeting_ID', models.IntegerField()),
                ('number_of_participants', models.IntegerField()),
                ('name_of_participant', models.CharField(max_length=50)),
                ('meeting_materials', models.CharField(max_length=100)),
            ],
        ),
    ]
