# Generated by Django 3.2.6 on 2021-11-01 02:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='health',
            name='address',
            field=models.CharField(default='1244 Park Street', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='health',
            name='dose',
            field=models.CharField(default='1244 Park Street', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='health',
            name='email',
            field=models.EmailField(default='zanetwill@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='health',
            name='medicine',
            field=models.CharField(default='Codine', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='health',
            name='time_to_take',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
