# Generated by Django 3.2.6 on 2021-11-29 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_item_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('F', 'Food'), ('E', 'Entertainment'), ('T', 'Travel'), ('S', 'Sport'), ('Ed', 'Education')], default='E', max_length=2),
            preserve_default=False,
        ),
    ]
